name: Publish to NPM
on:
  push:
    branches:
      - ylm-experiment-2
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: npm-publish
        with:
          token: ${{ secrets.MODEL_SMAL_WEBISTE_TOKEN }}
          access: 'public'